services:
  trunkpg:
    image: zabbix/zabbix-server-pgsql:trunk-alpine
    container_name: trunkpg
    environment:
      DB_SERVER_HOST: 10.88.74.17
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: trunk
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix
      TZ: Europe/Riga
      ZBX_ALLOWUNSUPPORTEDDBVERSIONS: '1'
      ZBX_CACHESIZE: 256M
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTALERTERS: '1'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '0'
      ZBX_STARTHTTPPOLLERS: '0'
      ZBX_STARTLLDPROCESSORS: '1'

      ZBX_STARTPOLLERS: '0'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '0'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTPROXYPOLLERS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

      ZBX_STARTPINGERS: '0'

    ports:
      - "11151:10051"
    networks:
      podnet:
        ipv4_address: 10.88.2.111
    tty: true
    restart: unless-stopped

  trunkprx:
    image: zabbix/zabbix-proxy-sqlite3:trunk-alpine
    container_name: trunkprx
    environment:
      ZBX_HOSTNAME: 'passive'
      ZBX_PROXYMODE: '1'
      TZ: Europe/Riga
      ZBX_CACHESIZE: 256M
      ZBX_SERVER_HOST: 10.88.2.111
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '0'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '0'
      ZBX_STARTHTTPAGENTPOLLERS: '0'
      ZBX_STARTHTTPPOLLERS: '0'
      ZBX_STARTPINGERS: '0'
      ZBX_STARTPOLLERS: '0'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '0'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "21151:10051"
    networks:
      podnet:
        ipv4_address: 10.88.3.111
    tty: true
    restart: unless-stopped


  trunkweb:
    image: zabbix/zabbix-web-nginx-pgsql:trunk-alpine
    container_name: trunkweb
    environment:
      DB_SERVER_HOST: '10.88.74.17'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'trunk'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      ZBX_SERVER_HOST: '10.88.2.111'
      ZBX_SERVER_PORT: '10051'
      PHP_TZ: 'Europe/Riga'

    ports:
      - "8011:8080"
    networks:
      podnet:
        ipv4_address: 10.88.1.111
    tty: true
    restart: unless-stopped


networks:
  podnet:
    name: DockerInternalNet
    external: true

