services:

# ldap directory
  ldap:
    image: bgmot42/openldap-server:0.1.1
    container_name: ldap

    ports:
      - '3389:389'
      - '6636:636'
    networks:
      podnet:
        ipv4_address: '10.88.53.27'
    tty: true
    restart: unless-stopped

# ldap GUI
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin

    environment:
      PHPLDAPADMIN_LDAP_HOSTS: '10.88.53.27'

    ports:
      - '8081:80'
      - '4443:443'
    networks:
      podnet:
        ipv4_address: '10.88.53.28'


    tty: true
    restart: unless-stopped

networks:
  podnet:
    name: DockerInternalNet
    external: true

